# Generated by Django 4.1.4 on 2023-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_alter_movie_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(db_column='movie_name', db_index=True, max_length=126),
        ),
    ]
