# Generated by Django 4.1.6 on 2023-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_actor_movieactor_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(db_column='description', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(db_column='name', db_index=True, default='ttt', max_length=126),
            preserve_default=False,
        ),
    ]
